const MessageActionTypes = {
  GET_MESSAGES_START: 'GET_MESSAGES_START',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',

  ADD_MESSAGES_START: 'ADD_MESSAGES_START',
  ADD_MESSAGES_SUCCESS: 'ADD_MESSAGES_SUCCESS',
  ADD_MESSAGES_FAILURE: 'ADD_MESSAGES_FAILURE',

  GET_REALTIME_MSG_START: 'GET_REALTIME_MSG_START',
  GET_REALTIME_MSG_SUCCESS: 'GET_REALTIME_MSG_SUCCESS',
  GET_REALTIME_MSG_FAILURE: 'GET_REALTIME_MSG_FAILURE',

  SET_MSG_SEEN_START: 'SET_MSG_SEEN_START',
  SET_MSG_SEEN_SUCCESS: 'SET_MSG_SEEN_SUCCESS',
  SET_MSG_SEEN_FAILURE: 'SET_MSG_SEEN_FAILURE',

  GET_NOTIFICATION_START: 'GET_NOTIFICATION_START',
  GET_NOTIFICATION_SUCCESS: 'GET_NOTIFICATION_SUCCESS',
  GET_NOTIFICATION_FAILURE: 'GET_NOTIFICATION_FAILURE',

  ADD_REALTIME_NOTIFICATION_START: 'ADD_REALTIME_NOTIFICATION_START',
  ADD_REALTIME_NOTIFICATION_SUCCESS: 'ADD_REALTIME_NOTIFICATION_SUCCESS',

  DELETE_NOTIFICATION_START: 'DELETE_NOTIFICATION_START',
  DELETE_NOTIFICATION_SUCCESS: 'DELETE_NOTIFICATION_SUCCESS',

  CLEAR_UP_MESSAGE: 'CLEAR_UP_MESSAGE',
  UNSUBSCRIBE_NOTIFICATION: 'UNSUBSCRIBE_NOTIFICATION',
};

export default MessageActionTypes;
