const userTypes = {
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  GOOGLE_SIGN_IN_SUCCESS: 'GOOGLE_SIGN_IN_SUCCESS',
  GOOGLE_SIGN_IN_FAILURE: 'GOOGLE_SIGN_IN_FAILURE',

  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

  CHANGE_PROFILE_START: 'CHANGE_PROFILE_START',
  CHANGE_PROFILE_SUCCESS: 'CHANGE_PROFILE_SUCCESS',
};

export default userTypes;
