const channelActionTypes = {
  DISPLAY_USER_LIST_START: 'DISPLAY_USER_LIST_START',
  DISPLAY_USER_LIST_SUCCESS: 'DISPLAY_USER_LIST_SUCCESS',
  DISPLAY_USER_LIST_FAILURE: 'DISPLAY_USER_LIST_FAILURE',

  DISPLAY_ADDED_CHANNEL_START: 'DISPLAY_ADDED_CHANNEL_START',
  DISPLAY_ADDED_CHANNEL_SUCCESS: 'DISPLAY_ADDED_CHANNEL_SUCCESS',
  DISPLAY_ADDED_CHANNEL_FAILURE: 'DISPLAY_ADDED_CHANNEL_FAILURE',

  CREATE_CHANNEL_START: 'CREATE_CHANNEL_START',
  CREATE_CHANNEL_SUCCESS: 'CREATE_CHANNEL_SUCCESS',
  CREATE_CHANNEL_FAILURE: 'CREATE_CHANNEL_FAILURE',

  SET_CURRENT_CHANNEL_START: 'SET_CURRENT_CHANNEL_START',
  SET_CURRENT_CHANNEL_SUCCESS: 'SET_CURRENT_CHANNEL_SUCCESS',

  SET_CURRENT_CHANNEL_NULL_START: 'SET_CURRENT_CHANNEL_NULL_START',
  SET_CURRENT_CHANNEL_NULL_SUCCESS: 'SET_CURRENT_CHANNEL_NULL_SUCCESS',

  UNSUBSCRIBE_CHANNEL: 'UNSUBSCRIBE_CHANNEL',
};

export default channelActionTypes;
